package gui;

import bl.DiceTableModel;
import bl.KniffelTableModel;


/**
 *
 * @author Matthias
 */
public class KniffelGUI extends javax.swing.JFrame {

    KniffelTableModel kniffelModel = new KniffelTableModel();
    DiceTableModel diceModel = new DiceTableModel();
    
    public KniffelGUI() {
        initComponents();
        jTable1.setModel(kniffelModel);
        jTable1.setDefaultRenderer(Object.class, new KniffelTableRenderer());
        tableDice.setModel(diceModel);
        tableDice.setDefaultRenderer(Object.class, new DiceTableRenderer());
        tableDice.setRowHeight(40);
        tableDice.getTableHeader().setUI(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDice = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDice = new javax.swing.JTable();
        btToss = new javax.swing.JButton();
        pnSelection = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnPoints = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfUpSum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfUpBon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfBotSum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfSum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableDice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDice);

        javax.swing.GroupLayout pnDiceLayout = new javax.swing.GroupLayout(pnDice);
        pnDice.setLayout(pnDiceLayout);
        pnDiceLayout.setHorizontalGroup(
            pnDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDiceLayout.setVerticalGroup(
            pnDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btToss.setText("würfeln");
        btToss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTossActionPerformed(evt);
            }
        });

        pnSelection.setBorder(javax.swing.BorderFactory.createTitledBorder("Gewinnkarte"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnSelectionLayout = new javax.swing.GroupLayout(pnSelection);
        pnSelection.setLayout(pnSelectionLayout);
        pnSelectionLayout.setHorizontalGroup(
            pnSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSelectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnSelectionLayout.setVerticalGroup(
            pnSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSelectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnPoints.setBorder(javax.swing.BorderFactory.createTitledBorder("Punkte"));
        pnPoints.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        jLabel1.setText("Obere Summe:");
        pnPoints.add(jLabel1);

        tfUpSum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUpSum.setText("0");
        pnPoints.add(tfUpSum);

        jLabel2.setText("Oberer Bonus:");
        pnPoints.add(jLabel2);

        tfUpBon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUpBon.setText("0");
        pnPoints.add(tfUpBon);

        jLabel3.setText("Untere Summe:");
        pnPoints.add(jLabel3);

        tfBotSum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBotSum.setText("0");
        pnPoints.add(tfBotSum);

        jLabel4.setText("Gesamt-Punkte");
        pnPoints.add(jLabel4);

        tfSum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSum.setText("0");
        pnPoints.add(tfSum);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnDice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btToss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnPoints, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btToss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        kniffelModel.toggleSelected(jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btTossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTossActionPerformed
        diceModel.toss();
    }//GEN-LAST:event_btTossActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KniffelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KniffelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KniffelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KniffelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KniffelGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btToss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnDice;
    private javax.swing.JPanel pnPoints;
    private javax.swing.JPanel pnSelection;
    private javax.swing.JTable tableDice;
    private javax.swing.JTextField tfBotSum;
    private javax.swing.JTextField tfSum;
    private javax.swing.JTextField tfUpBon;
    private javax.swing.JTextField tfUpSum;
    // End of variables declaration//GEN-END:variables
}
